### ISSUE TITLE
MSharp.AddNew - Adding entities issues

### ISSUE THREAD

**Issue by StephenAtGeeks** [Geeksltd/MSharp.Docs#38]
Some issues with adding entities on AddNew extension:

If I right click on a CMS folder and add a new entity and name it "Customer" it will create a folder called "CMS`" and put the customer entity in there? This is wrong.

If I right click on the #Model solution and do add new -> entity - nothing happens or gets creating.

What I believe should happen:

If you right-click a folder and add an entity, just add the file into that folder as its the user's decision to right click that folder.

If you right-click the #Model solution and add new from there - just add it in the base of the solution.

**Comment by pharzath** [comment]
First of all, I think your testing VSIX version was a little older than the final release in that time because I have solved that error before. but when I want to test the VSIX, I can realize that MSharp.exe has been changed and now I should add generated file(s) to project items otherwise they only created and are not counted in the projects at all, in addition to 2-3 changes in folder argument and ...
Anyway, everything works well so the issue is SOLVED!

**Comment by StephenAtGeeks** [comment]
Fixed.
