### ISSUE TITLE
Intellisense - Have to finish quotations for alt-I to work.

### ISSUE THREAD

**Issue by StephenAtGeeks** [Geeksltd/MSharp.Docs#39]
An annoyance with the extension:

You have to first finish the quotations then add your semi-colon before the alt - I actually opens.

Would it be possible to have this work without this requirement?

**Comment by pharzath** [comment]
Actually, I'm afraid that couldn't be possible because when we write a sentence in C# then LightBulb actions only automatically populated when a sentence can be parsed, So just after closing quote the Lightbulb populated by "ISuggestedActionsSource" and "ISuggestedActionsSourceProvider" 
But I'll try to find a solution in the meantime.

**Comment by StephenAtGeeks** [comment]
That is okay - don't spend any more time on this item finding a better solution, please move onto other more important issues :)

thank you.

**Comment by pharzath** [comment]
In fact, because of all VSIX syntax detection processes were implemented by Roslyn so we are not able to break Roslyn syntax/semantic parsing rules.
